language: python

python:
  - "2.7"
  - "2.6"

env:
  - DJANGO=1.5.1

before_install:
  - export DJANGO_SETTINGS_MODULE=podbadge.settings
  - export PIP_USE_MIRRORS=true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script:
  - python manage.py test podbadge